import "./globals.css";
import { poppins } from "@/constants/fonts";
import { Metadata } from "next";
import { AnalyticsProvider } from "@/context/AnalyticsProvider";
import { RootProvider } from "fumadocs-ui/provider";
import { Suspense } from "react";
import { Progress } from "@/components/Progress";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import GlobalKeyBinderProvider from "@/context/GlobalKeyBinderProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className="scrollbar-hidden overflow-x-hidden scroll-smooth dark"
      lang="en"
      suppressHydrationWarning={true}
    >
      <TooltipProvider>
        <AnalyticsProvider>
          <body
            className={`${poppins.className} antialiased overflow-x-hidden`}
          >
            <Suspense fallback={null}>
              <Progress />
            </Suspense>
            <Toaster />
            <RootProvider search={{ enabled: false }}>
              <GlobalKeyBinderProvider>{children}</GlobalKeyBinderProvider>
            </RootProvider>
          </body>
        </AnalyticsProvider>
      </TooltipProvider>
    </html>
  );
}
